Rezept:
    Prep Time: 25 Minuten
    Baking Time: 75 Min + 1 Std. + 8 Std. im Kühlschrank kühlen (über Nacht)
    Difficulty: Mittel
    Portionen: ca 16

Zutaten:
    Boden:
        - "15-20 graham crackers, aber da man sie hier nicht bekommt: ich hab Hobbits von Brandt benutzt, lecker!"
        - "ca 90ml (6 tablespoons) geschmolzene Butter"
        - "Butter zum Einstreichen der Springform (wichtig: Raumtemperatur)"
        - "30g Zucker"
        - "1 Prise Salz"
    Für den Cheesecake (26cm):
        - "9 x 175g Pkg. Philadelphia Doppelrahmstufe Frischkäse (verrückt…) – (Raumtemperatur)"
        - 428g Zucker
        - 70g Mehl
        - 240ml Sauerrahm (Raumtemperatur)
        - 7ml (1 1/2 teaspoons) Vanilleextrakt
        - 5 große Eier (Raumtemperatur)

Anleitung:
    - 1. Heize Deinen Ofen auf 180 Grad vor.
    - 2. Die Springform mit der Butter genügend einfetten.
    - 3. Nun das Äußere der Springform (den Boden auch) in Alufolie wickeln, am besten 2x, so kann weder das heiße Wasser nicht in die Springform eintreten, noch evtl. Flüssigkeit aus der Springform entweichen.
    - 4. Um den Cheesecakeboden zu machen, zerkleinert die Kekse in einem Zerkleinerer oder zerstampft sie zu kleinen Krümeln in einer größeren Schale. Hauptsache am Ende kommen feine Krümel bei raus. Nun kannst du die Krümel mit der geschmolzenen Butter und dem Zucker in einer Schale vermengen.
    - 5. Der Krümelzucker-Mix kommt nun in die Springform. Ich habe ein Glas genommen um den Boden eben zu machen, es geht aber auch ein Fleischstampfer oder jegliches Utensil, was flach ist.
    - 6. Nun kommt die Springform für ca. 15 Minuten in den Kühlschrank. Dann, auf einem Backblech, für 15 Minuten in den Backofen, bis der Boden schön fest ist. Danach bitte komplett abkühlen lassen.
    - 7. Jetzt geht’s ans Eingemachte. Die große Menge an Philadelphia (für mich die Nummer 1) Frischkäse kommt jetzt in eine große Schüssel. Nun mixt ihr den Frischkäse gut durch bis er fluffig ist. Ca. 3 Minuten.
    - 8. In einer anderen Schüssel verrührt ihr nun mit einem Schneebesen den Zucker und das Mehl miteinander. Bei niedriger Stufe nun den Zucker-Mix nach und nach in die Schüssel mit dem Frischkäse geben. Mixe so lang bis alles gut vermengt ist. Ein paar Minuten sollten es schon sein.
    - 9. Jetzt den Sauerrahm und das Vanilleextrakt hinzugeben. Wieder gut durchmixen, bis alles vermengt ist.
    - 10. Nun ein Ei nach dem Anderen dazugeben. Achte drauf, dass du nicht zu lange mixt. Nur so das die Eier gerade so mit dem Rest vermengt sind.
    - 11. Jetzt bist du fast fertig. Jetzt kann die Frischkäsefüllung in die Springform gegossen werden. Die Springform kommt nun in einen großen Bräter wie ihr auf dem Foto sehen könnt. Meine Springform hat gerade so reingepasst.
    - 12. Ganz vorsichtig nun das kochende Wasser in den Bräter geben, so viel das die Hälfte der Springform im Wasser steht. Das kochenede Wasser bewirkt, dass der Cheesecake keine unschönen Risse bekommt. Bei mir hat es was gebracht. Ich hoffe, bei Dir auch.
    - 13. Nun wird dein Cheesecake für 45 Minuten gebacken (mittlere Schiene, Ober-/Unterhitze). Danach die Temperatur auf 160 Grad reduzieren und nochmals für 30 Minuten backen, bis er recht fest ist, nur in der Mitte noch ein wenig wackelig zu sein scheint.
    - 14. Nun bleibt der Cheesecake noch eine ganze Stunde bei halboffener Ofentür im Ofen.
    - 15. Jetzt kannst du ihn rausnehmen, auf ein Gitterrost und komplett abkühlen lassen. Die Springform noch nicht lösen! Erst für ca. 6 Stunden oder wie ich es gemacht hab, über Nacht, den Cheesecake im Kühlschrank ruhen lassen. Dann bekommst du ein perfekteres Ergebnis.
    - |
        16. Bevor du die Springform entfernst, gehe doch mit einem Messer nochmal am Rand entlang, damit er sich besser lösen kann. Wenn du nun Stücke schneiden möchtest: Halte das Messer unter heißes Wasser oder tauche es in heißes Wasser, dann schneide ein Stück ab. Bevor du ein neues Stück schneidest, wiederhol den Vorgang. So bekommt man gleichmäßige, glatte Schnitte ohne das Krümel vom vorherigen Stück auf das neue Stück gelangen.
